app:
    resource: '@AppBundle/Controller'
    type: annotation

default_index:
    path:    /
    defaults: { _controller: AppBundle:Default:index }

lucky_number:
    path:    /lucky/number/{max}
    defaults: { _controller: AppBundle:Lucky:number }

lucky_form:
    path:   /lucky/form
    defaults: { _controller: AppBundle:Lucky:form }

lucky_find:
    path:   /lucky/find
    defaults: { _controller: AppBundle:Lucky:find }

lucky_show:
    path:   /lucky/show
    defaults: { _controller: AppBundle:Lucky:show }

lucky_erase:
    path:   /lucky/erase
    defaults: { _controller: AppBundle:Lucky:erase }

lucky_update:
    path:   /lucky/update
    defaults: { _controller: AppBundle:Lucky:update }

task_new:
    path:   /task/new
    defaults: { _controller: AppBundle:Task:new }

task_show:
    path:   /task/show
    defaults: { _controller: AppBundle:Task:show }