app:
    resource: '@AppBundle/Controller'
    type: annotation

default_index:
    path:    /
    defaults: { _controller: AppBundle:Default:index }

lucky_number:
    path:    /lucky/number/{max}
    defaults: { _controller: AppBundle:Lucky:number }

lucky_form:
    path:   /lucky/form
    defaults: { _controller: AppBundle:Lucky:form }

lucky_find:
    path:   /lucky/find
    defaults: { _controller: AppBundle:Lucky:find }

lucky_show:
    path:   /lucky/show
    defaults: { _controller: AppBundle:Lucky:show }