app:
    resource: '@AppBundle/Controller'
    type: annotation

default_index:
    path:    /
    defaults: { _controller: AppBundle:Default:index }

lucky_number:
    path:    /lucky/number/{max}
    defaults: { _controller: AppBundle:Lucky:number }

lucky_form:
    path:   /lucky/form
    defaults: { _controller: AppBundle:Lucky:form}

#lucky_db:
#    path:   /lucky/db
#    defaults: { _controller: AppBundle:Lucky:db}