# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.exception_controller:
        class: AppBundle\Controller\ExceptionsController
        arguments: ['@twig', '%kernel.debug%']

    app.message_generator:
        class:  AppBundle\Service\MessageGenerator
        arguments:  []

    app.exception_listener:
        class:  AppBundle\EventListener\ExceptionListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception }

    app.exception_subscriber:
        class:  AppBundle\EventSubscriber\ExceptionSubscriber
        tags:
          - { name: kernel.event_subscriber }