AppBundle\Entity\Number:
    type: entity
    table: number
    repositoryClass: AppBundle\Repository\NumberRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime

        number:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }